### ISSUE TITLE
README.md: Update build steps

### ISSUE THREAD

**Issue by palash25** [jecolon/zigstr#5]
the readme mentions to add the following code in `build.zig`

```zig
const cow_list = std.build.Pkg{ .name = "cow_list", .source = .{ .path = "libs/zigstr/libs/cow_list/src/main.zig" } };
const ziglyph = std.build.Pkg{ .name = "ziglyph", .source = .{ .path = "libs/zigstr/libs/ziglyph/src/ziglyph.zig" } };
const Zigstr = std.build.Pkg{
    .name = "Zigstr",
    .source = .{ .path = "libs/zigstr/src/Zigstr.zig" },
    .dependencies = &[_]std.build.Pkg{ cow_list, ziglyph },
};
exe.addPackage(Zigstr);
```

But this fails, there seems to be no `Pkg` struct in the `build` library https://github.com/ziglang/zig/blob/master/lib/std/Build.zig  I guess something got deprecated in the stdlib and this README wasn't updated, it would be helpful i you could.

**Comment by jecolon** [comment]
Hello. I think you missed the heading right at the top of the README:

Zig Version
This code will work with Zig version 0.10 stable; it is not yet updated to work with the latest master dev build.

It should work with 0.10. I'm waiting for 0.11 stable to come out so I can update to the new language and build system features.

**Comment by palash25** [comment]
Oh yes. You are right. Sorry for the noise. Feel free to close it.
